# PostgreSQL 連線配置
spring.datasource.url=jdbc:postgresql://localhost:5432/search_method_db
spring.datasource.username=smc_user
spring.datasource.password=smc_password
spring.jpa.hibernate.ddl-auto=update

# Elasticsearch 連線配置
spring.elasticsearch.uris=http://localhost:9200

# 顯示 SQL (實驗時方便觀察)
spring.jpa.show-sql=true